# EXPO needs a ip to run QRCode properly
# use make, do not use docker-compose up alone

version: "3"
services:
  front:
    build: copilot
    command: bash -c "bash"
    ports:
      - "19000:19000"
      - "19001:19001"
    env_file:
      - .env
    volumes:
      - ./copilot/:/app
    stdin_open: true
    tty: true 